server:
  port: 8081


spring:
  profiles.active: dev
  database: h2
  console: true

  datasource:
    url: jdbc:h2:mem:ecommerce;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console